import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,Plus,Paperclip,Send,LockKeyhole,Users,MessageCircle,FolderClosed,LogOut,Palette}from'lucide-react';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const req=async(path,token,options={})=>{const r=await fetch(API+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});if(!r.ok)throw new Error((await r.json()).detail||'Request failed');return r.json()};
function Auth({onAuth}){const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',username:'',phone:'',password:''}),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');try{const data=await req(`/auth/${mode}`,null,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('vpm_token',data.token);onAuth(data.token,data.user)}catch(x){setError(x.message)}};return <div className="auth"><form onSubmit={submit}><div className="mark big">V</div><h1>Private Media</h1><p>Private conversations. Nothing public.</p>{mode==='register'&&<><input placeholder="Name" onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="$username" onChange={e=>setForm({...form,username:e.target.value})}/></>}<input placeholder="Phone number" onChange={e=>setForm({...form,phone:e.target.value})}/><input type="password" placeholder="Password" onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<small className="error">{error}</small>}<button className="primary">{mode==='login'?'Sign in':'Create account'}</button><button type="button" className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account':'Already have an account?'}</button></form></div>}
function App(){const[token,setToken]=useState(localStorage.getItem('vpm_token')||''),[me,setMe]=useState(null),[contacts,setContacts]=useState([]),[groups,setGroups]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState([]),[tab,setTab]=useState('chats');
const load=async t=>{try{const[u,c,g]=await Promise.all([req('/me',t),req('/contacts',t),req('/groups',t)]);setMe(u);setContacts(c);setGroups(g)}catch{localStorage.removeItem('vpm_token');setToken('')}};useEffect(()=>{if(token)load(token)},[token]);
useEffect(()=>{if(!token)return;const ws=new WebSocket(`${API.replace('http','ws')}/ws?token=${token}`);ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='message'&&active?.id===d.from.id)setMessages(m=>[...m,{id:d.id,sender_id:d.from.id,body:d.body}]);};return()=>ws.close()},[token,active?.id]);
useEffect(()=>{if(!active||!token)return;req(active.group?`/messages/group/${active.id}`:`/messages/private/${active.id}`,token).then(setMessages).catch(()=>setMessages([]))},[active,token]);
useEffect(()=>{const id=setTimeout(()=>{if(query.trim())req(`/users/search?q=${encodeURIComponent(query)}`,token).then(setResults);else setResults([])},250);return()=>clearTimeout(id)},[query,token]);
const add=async u=>{await req('/contacts',token,{method:'POST',body:JSON.stringify({username:u.username})});setQuery('');setResults([]);load(token)};
const send=async()=>{if(!active||!text.trim())return;const body=text.trim();setText('');const endpoint=active.group?`/messages/group/${active.id}`:`/messages/private/${active.id}`;const r=await req(endpoint,token,{method:'POST',body:JSON.stringify({body})});setMessages(m=>[...m,{id:r.id,sender_id:me.id,body}])};
const createGroup=async()=>{const name=prompt('Private group name');if(!name)return;await req('/groups',token,{method:'POST',body:JSON.stringify({name,members:[]})});load(token);setTab('groups')};
const logout=()=>{localStorage.removeItem('vpm_token');setToken('');setMe(null)};const color=async()=>{const c=prompt('Text color hex (#ffffff)',me.accent_color);if(!c)return;const u=await req('/me/color',token,{method:'PATCH',body:JSON.stringify({color:c})});setMe(u)};
if(!token||!me)return <Auth onAuth={(t,u)=>{setToken(t);setMe(u)}}/>;const items=tab==='groups'?groups.map(g=>({...g,group:true})):contacts;
return <main className="shell" style={{'--user-color':me.accent_color}}><aside className="sidebar"><div className="brand"><div className="mark">V</div><div><strong>Private Media</strong><span>{me.username}</span></div><button className="icon" onClick={logout}><LogOut size={17}/></button></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find $username"/></div>{results.length>0&&<div className="results">{results.map(u=><button key={u.id} onClick={()=>add(u)}>{u.username}<span>+ contact</span></button>)}</div>}<div className="section-title"><span>{tab==='groups'?'Private groups':'Contacts'}</span><button onClick={tab==='groups'?createGroup:()=>document.querySelector('.search input')?.focus()}><Plus size={18}/></button></div><div className="chat-list">{items.map(x=><button key={(x.group?'g':'u')+x.id} className={`chat-row ${active?.id===x.id&&active?.group===x.group?'active':''}`} onClick={()=>setActive(x)}><div className="avatar">{x.group?<Users size={18}/>:x.username?.slice(1,2).toUpperCase()}</div><div className="chat-copy"><strong>{x.group?x.name:x.username}</strong><p>{x.group?'Private group':'Private contact'}</p></div></button>)}</div><nav className="nav"><button className={tab==='chats'?'selected':''} onClick={()=>setTab('chats')}><MessageCircle size={18}/>Chats</button><button className={tab==='groups'?'selected':''} onClick={()=>setTab('groups')}><Users size={18}/>Groups</button><button onClick={color}><Palette size={18}/>Color</button></nav></aside><section className="conversation">{active?<><header><div className="avatar">{active.group?<Users size={18}/>:active.username?.slice(1,2).toUpperCase()}</div><div><strong>{active.group?active.name:active.username}</strong><span>{active.group?'Private group':'Private conversation'}</span></div><LockKeyhole className="lock" size={17}/></header><div className="messages"><div className="privacy"><LockKeyhole size={16}/>Private space</div>{messages.map(m=><div key={m.id} className={`bubble ${m.sender_id===me.id?'mine':''}`}><p>{m.body}</p><small>{m.sender_id===me.id?'Sent ✓':'Received'}</small></div>)}</div><div className="composer"><label><Paperclip size={20}/><input type="file" hidden/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Message privately..."/><button className="send" onClick={send}><Send size={19}/></button></div></>:<div className="empty"><LockKeyhole size={30}/><h2>Your private space</h2><p>Add a $username or create a private group.</p></div>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);